
const members = [
    {
      name: "Aarohi Manchanda",
      position: "Convener Committee",
      team: "ECcc",
      behance:"test",
      github:"",
      linkedin:"",
      instagram:"test",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Mahi Jain",
      position: "Convener Committee",
      team: "ECcc",
      behance:"",
      github:"",
      linkedin:"test",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Mitesh Sharma",
      position: "Convener Committee",
      team: "ECcc",
      behance:"",
      github:"https://github.com/",
      linkedin:"",
      instagram:"test",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Manya Sharma",
      position: "Convener Committee",
      team: "ECcc",
      behance:"test",
      github:"",
      linkedin:"test",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Aishwary Shree",
      position: "Convener Committee",
      team: "ECcc",
      behance:"test",
      github:"",
      linkedin:"test",
      instagram:"test",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Vaishnavi Parihar",
      position: "Convener Committee",
      team: "ECcc",
      behance:"",
      github:"",
      linkedin:"test",
      instagram:"test",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Vikramditya Hiran",
      position: "Events",
      team: "EC",
      behance:"",
      github:"test",
      linkedin:"",
      instagram:"test",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Ritvik Chawla",
      position: "Events",
      team: "EC",
      behance:"",
      github:"test",
      linkedin:"test",
      instagram:"test",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Rishav Agarwal",
      position: "Sponsorship",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Utkarsh Rana",
      position: "Curations",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Prayas Godara",
      position: "Marketing",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Utkarsh Rana",
      position: "Marketing",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Tanishaa Sinha",
      position: "Logistics",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Archie Sharma",
      position: "Content",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Hardik Agarwal",
      position: "Finance",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Yash Panchigar",
      position: "Hospitality",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Jasjappan Singh",
      position: "Graphic Design",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Sejal Kothari",
      position: "Graphic Design",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Suyash Patel",
      position: "Media",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Jeevanshi Bansal",
      position: "Crafts",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Jasjappan Singh",
      position: "Developer",
      team: "EC",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Aryan Kamnoj",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/3cdfb5ea-66fb-4c0d-8b5a-e4c20d442103_Aryan_+Joint+Community+manager+.jpeg?auto=compress,format",
    },
    {
      name: "Mehul Singhvi",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/6280e86c-751d-4e64-a2a1-4c8720613933_Mehul_Senior+Program+Coordinator+.webp?auto=compress,format",
    },
    {
      name: "Lokesh Kothari",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/b2363452-78c3-4709-ac77-76fa09a086db_LokesshKothari+SeniorProgramCoordinator.jpg?auto=compress,format",
    },
    {
      name: "Pratyaksh Singhal",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/0f4f4593-8bad-468f-9098-d057beee4924_Pratyaksh_senior+coordinator+of+corporate+affairs.jpg?auto=compress,format",
    },
    {
      name: "Divyansh Jain",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/cedc9a12-2a3a-438b-9fdc-ee04ce365696_Mitisha+mittal_senior+promotions+coordinator+ieee+sb.jpg?auto=compress,format",
    },
    {
      name: "Jitendra Choudhary",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/b54ad3f3-112c-4a15-abff-e6ab8c4b7093_Jitendra+Choudhary_Sr.+coordinator-Logistics.jpg?auto=compress,format",
    },
    {
      name: "Divya Srivastva",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/02c2a039-0b3e-4f29-a561-928ceab00599_RutujaKadam_SeniorPromotionsCoordinator.jpg?auto=compress,format",
    },
    {
      name: "Rutuja Kadam",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/02c2a039-0b3e-4f29-a561-928ceab00599_RutujaKadam_SeniorPromotionsCoordinator.jpg?auto=compress,format",
    },
    {
      name: "Pravartika Mishra",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/8a328c04-dc53-4796-8b56-d849c95e0594_Pravartika_senior+community+manager.jpg?auto=compress,format",
    },
    {
      name: "Aastha",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Shekhar Pilania",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/4cc855d9-00c2-4ff1-aee6-88aeaa717ad5_Shekhar_senior+program+coordinator.jpg?auto=compress,format",
    },
    {
      name: "Rajveer Sanghavi",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Rishabh Bassi",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/9b36e700-6aa5-433c-9572-e8092e07610e_Rishabhbass+Joint+head+of+graphic+design.jpeg?auto=compress,format",
    },
    {
      name: "Mahika Khanna",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Khushi Gupta",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Adeeb",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Anchal Tyagi",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/6f20e76c-4224-4a4f-92db-7b42a716449d_Aanchal+Mittal_Head+of+corporate+affairs.jpg?auto=compress,format",
    },
    {
      name: "Sonakshi Arora",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Kshiti Malla",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Aman Sethi",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Mohit Sinha",
      position: "Developer",
      team: "CCevents",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Aanchal Mittal",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/6f20e76c-4224-4a4f-92db-7b42a716449d_Aanchal+Mittal_Head+of+corporate+affairs.jpg?auto=compress,format",
    },
    {
      name: "Anish Kothari",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/e4a01a93-d850-4cf1-991f-d63d5893b20d_Anish+Kothari_+Senior+Editorial+Coordinator.jpg?auto=compress,format",
    },
    {
      name: "Vedika Parwal",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/cf1f2d7b-a033-442b-811d-24da175459c9_Vedika+Parwal_Joint+Head+Corporate+Affairs+.jpg?auto=compress,format",
    },
    {
      name: "Atul Raj Sharma",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/59f97e47-ff20-4c66-8306-90568ab88cbb_Atul+Raj+Sharma_+Head+of+Programs_.jpg?auto=compress,format",
    },
    {
      name: "Tanash Sultania",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/c70cc1fc-e15b-47ab-92fd-380730c2bcb6_Tanash+Sultania+_+senior+coordinator+of+curations_.jpg?auto=compress,format",
    },
    {
      name: "Vidit Parashar",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Yuvraj Vasudeva",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Arnav Rishi Raj",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Vanshika Singh Andotra",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Saloni Agrawal",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Shriyanshi Srivastava",
      position: "Developer",
      team: "CCsponsorship",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Aastha Gupta",
      position: "Developer",
      team: "CCcurations",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/4298c14f-4143-4efc-9e4d-b89c4683e52c_Aastha+Gupta_joint+head+of+curations.jpg?auto=compress,format",
    },
    {
      name: "Ishaan Gulrajani",
      position: "Developer",
      team: "CCcurations",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Anant Sharma",
      position: "Developer",
      team: "CCcurations",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/0b444b12-2053-4932-8477-f04bf45b2c32_Anant+Sharma+_+senior+curations+coordinator.jpg?auto=compress,format",
    },
    {
      name: "Ridhi Makharia",
      position: "Developer",
      team: "CCcurations",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Anoushka Goyal",
      position: "Developer",
      team: "CCcurations",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Drishti Singh",
      position: "Developer",
      team: "CCcurations",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Manya Khater",
      position: "Developer",
      team: "CCcurations",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Kaushambika Chillar",
      position: "Developer",
      team: "CCcurations",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Yoshe Vijay",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/cf654728-e6bd-4678-8a50-4b055b949326_Yoshe+Vijay+senior+social+media+coordinator+.jpg?auto=compress,format",
    },
    {
      name: "Sriansh Raj",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Aastha Tandon",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/cdbd624e-ef95-4434-94e1-187a244b69ab_AasthaTandon_SeniorCoordinatorSocialMedia.jpg?auto=compress,format",
    },
    {
      name: "Yasir Tanveer",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/17727974-e4a0-4bd4-ad4e-8208154ba7b7_Yasir_social+media+senior+coordinator.jpg?auto=compress,format",
    },
    {
      name: "Aditya Pandey",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/cb2112fd-a2bf-4a2b-9999-3a3dc3f7402e_Aditya+Pandey_Joint+Head+of+Promotions.jpg?auto=compress,format",
    },
    {
      name: "Khushal Agarwal",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/3a39e812-b396-494b-935a-3449a4fd8580_Khushal+Agarwal_+Senior+Promotions+coordinator.jpg?auto=compress,format",
    },
    {
      name: "Samarth Bagga",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Nayonika Sharma",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/bf9b56b6-9de8-4651-8999-95bc9a379b73_Nayonika+Sharma_Joint+Head+of+Social+Media.jpeg?auto=compress,format",
    },
    {
      name: "Anshi Sangani",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Chahat Saluja",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Aditya Patil",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Aryaka",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Abhimanyu Bhasin",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Amisha Singh",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Veda Rathore",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Saloni Jain",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Priya Singh",
      position: "Developer",
      team: "CCmarketing",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Nachiketa Jha",
      position: "Developer",
      team: "CClogistics",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/477e0a51-2aa7-49ef-bf36-acee774ff025_Nachiketa_HeadOfLogistics.jpg?auto=compress,format",
    },
    {
      name: "Pukhraj Singh",
      position: "Developer",
      team: "CClogistics",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/6d58b678-4cf2-4a60-b8aa-ebe87af4b67f_Pukhraj+Singh_Senior+Coordinator+Logistics.jpg?auto=compress,format",
    },
    {
      name: "Piyush Bansal",
      position: "Developer",
      team: "CClogistics",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/ba1e669d-a8a8-4d8c-a5a3-6c3fa3b886f2_Piyush+bansal_senior+logistics+coordinator.png?auto=compress,format",
    },
    {
      name: "Kartik Taneja",
      position: "Developer",
      team: "CClogistics",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/2cb3268e-3212-44b3-9638-1aee25e69474_KartikTaneja_Senior+Promotions+Coordinator.jpg?auto=compress,format",
    },
    {
      name: "Prakhar Goel",
      position: "Developer",
      team: "CClogistics",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Khushi Ganatra",
      position: "Developer",
      team: "CClogistics",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Maulik",
      position: "Developer",
      team: "CClogistics",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Rajveer Dhakani",
      position: "Developer",
      team: "CClogistics",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Anushka Saxena",
      position: "Developer",
      team: "CClogistics",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Sonia Dighw",
      position: "Developer",
      team: "CCcontent",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/4dc0d0ee-5c96-4846-92e5-e9ee1e433c73_sonia+dighe-senior+editorial+coordinator_1.jpg?auto=compress,format",
    },
    {
      name: "Srivaishnavi",
      position: "Developer",
      team: "CCcontent",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/f7e98588-d456-4119-a98d-d2cf88dda2eb_Srivaishnavi_Joint-Head-of-Editorial.jpg?auto=compress,format",
    },
    {
      name: "Sanya Chaturvedi",
      position: "Developer",
      team: "CCcontent",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/fc774785-2eaf-45c8-8669-44b54a1d3f21_Sanya+Chaturvedi_Head+of+Editorial.jpg?auto=compress,format",
    },
    {
      name: "Avantika Yadav",
      position: "Developer",
      team: "CCcontent",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/072787e4-412b-423e-ae42-4e75c6e07369_Avantika_CommunityManager.jpg?auto=compress,format",
    },
    {
      name: "Mohd Asham",
      position: "Developer",
      team: "CCcontent",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Aditi Chandorkar",
      position: "Developer",
      team: "CCcontent",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Chestha Vasudeva",
      position: "Developer",
      team: "CCcontent",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Tanash Sultania",
      position: "Developer",
      team: "CCfinance",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/c70cc1fc-e15b-47ab-92fd-380730c2bcb6_Tanash+Sultania+_+senior+coordinator+of+curations_.jpg?auto=compress,format",
    },
    {
      name: "Lokesh Kothari",
      position: "Developer",
      team: "CCfinance",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/b2363452-78c3-4709-ac77-76fa09a086db_LokesshKothari+SeniorProgramCoordinator.jpg?auto=compress,format",
    },
    {
      name: "Jitendra Choudhary",
      position: "Developer",
      team: "CCfinance",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/b54ad3f3-112c-4a15-abff-e6ab8c4b7093_Jitendra+Choudhary_Sr.+coordinator-Logistics.jpg?auto=compress,format",
    },
    {
      name: "Dev Shalinkumar Agrawal",
      position: "Developer",
      team: "CCfinance",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Anish Ubriani",
      position: "Developer",
      team: "CCfinance",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Avanya Sagar",
      position: "Developer",
      team: "CCfinance",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Anshi Sangani",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Bhavya Bhardwaj",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/facf7f1b-ef9b-4ce3-8237-7e4e009568a3_Bhavya+Bhardwaj_Joint+head+of+media.jpg?auto=compress,format",
    },
    {
      name: "Avantika Yadav",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/072787e4-412b-423e-ae42-4e75c6e07369_Avantika_CommunityManager.jpg?auto=compress,format",
    },
    {
      name: "Pravartika Mishra",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/8a328c04-dc53-4796-8b56-d849c95e0594_Pravartika_senior+community+manager.jpg?auto=compress,format",
    },
    {
      name: "Aastha",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/81f54ebd-c669-432c-a568-2b322221d03d_Aastha_senior+promotions+coordinate.jpg?auto=compress,format",
    },
    {
      name: "Piyush Bansal",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/ba1e669d-a8a8-4d8c-a5a3-6c3fa3b886f2_Piyush+bansal_senior+logistics+coordinator.png?auto=compress,format",
    },
    {
      name: "Aditi Singh",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Ayush Tripathi",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Ankit Singh",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Vanisha Tyagi",
      position: "Developer",
      team: "CChospitality",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Ishan Rai Agarwal",
      position: "Developer",
      team: "CCgraphicdesign",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/76227aad-0a64-431b-b6fd-5a531911331b_Ishan+Rai+Agarwal+senior+design+cordinator_.jpg?auto=compress,format",
    },

    {
      name: "Vyom",
      position: "Developer",
      team: "CCgraphicdesign",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/ff0eab8e-8b54-4398-929a-7315335aafef_Vyom+Agrawal+senior+graphic+design+coordinator+.JPG?auto=compress,format",
    },
    {
      name: "Mahika Khanna",
      position: "Developer",
      team: "CCgraphicdesign",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Rishabh Bassi",
      position: "Developer",
      team: "CCgraphicdesign",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/9b36e700-6aa5-433c-9572-e8092e07610e_Rishabhbass+Joint+head+of+graphic+design.jpeg?auto=compress,format",
    },
    {
      name: "Aman Singh",
      position: "Developer",
      team: "CCgraphicdesign",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Saket",
      position: "Developer",
      team: "CCgraphicdesign",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Pragya Prasad",
      position: "Developer",
      team: "CCgraphicdesign",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Tanay Srivastava",
      position: "Developer",
      team: "CCwebdev",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/1899323c-2ba1-44ed-b2d6-b2a0bdff6ef8_tanay_webmaster.jpg?auto=compress,format",
    },
    {
      name: "Somesh Kumar",
      position: "Developer",
      team: "CCwebdev",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/8df03deb-38a5-4b91-9878-e07a97809409_Somesh_DeputyWebmaster.JPG?auto=compress,format",
    },
    {
      name: "Sriansh Raj",
      position: "Developer",
      team: "CCflyingsquad",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Yasir Tanveer",
      position: "Developer",
      team: "CCflyingsquad",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/17727974-e4a0-4bd4-ad4e-8208154ba7b7_Yasir_social+media+senior+coordinator.jpg?auto=compress,format",
    },
    {
      name: "Aastha Tandon",
      position: "Developer",
      team: "CCflyingsquad",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/cdbd624e-ef95-4434-94e1-187a244b69ab_AasthaTandon_SeniorCoordinatorSocialMedia.jpg?auto=compress,format",
    },
    {
      name: "Anant Sharma",
      position: "Developer",
      team: "CCflyingsquad",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/0b444b12-2053-4932-8477-f04bf45b2c32_Anant+Sharma+_+senior+curations+coordinator.jpg?auto=compress,format",
    },
    {
      name: "Anjali",
      position: "Developer",
      team: "CCcrafts",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Nitya Shah",
      position: "Developer",
      team: "CCcrafts",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Pukhraj Singh",
      position: "Developer",
      team: "CCcrafts",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/6d58b678-4cf2-4a60-b8aa-ebe87af4b67f_Pukhraj+Singh_Senior+Coordinator+Logistics.jpg?auto=compress,format",
    },
    {
      name: "Pravartika Mishra",
      position: "Developer",
      team: "CCcrafts",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/8a328c04-dc53-4796-8b56-d849c95e0594_Pravartika_senior+community+manager.jpg?auto=compress,format",
    },
    {
      name: "Suvijay Mahendru",
      position: "Developer",
      team: "CCmedia",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/28fe8a04-a9c8-43d2-b673-d1ef18c157ac_Suvijay_headofmedia.jpg?auto=compress,format",
    },
    {
      name: "Sanskar Singh",
      position: "Developer",
      team: "CCmedia",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Bhavya Bhardwaj",
      position: "Developer",
      team: "CCmedia",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://images.prismic.io/ieeemuj/facf7f1b-ef9b-4ce3-8237-7e4e009568a3_Bhavya+Bhardwaj_Joint+head+of+media.jpg?auto=compress,format",
    },
    {
      name: "Saksham Chaturvedi",
      position: "Developer",
      team: "CCmedia",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
    {
      name: "Shrrya Singh",
      position: "Developer",
      team: "CCmedia",
      behance:"",
      github:"",
      linkedin:"",
      instagram:"",
      image:
        "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fimages%2Fsearch%2Fuser%2F&psig=AOvVaw29_qPuKBLgqzf-iecMBtlF&ust=1664716184477000&source=images&cd=vfe&ved=0CAkQjRxqFwoTCJDg75iNv_oCFQAAAAAdAAAAABAD",
    },
  ];

export default members;